// <auto-generated />
using AGRental.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AGRental.Migrations
{
    [DbContext(typeof(AGRentalDBContext))]
    partial class AGRentalDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AGRental.Models.User", b =>
                {
                    b.Property<int>("User_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Username");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.HasKey("User_ID");

                    b.ToTable("Users");

                });
           

            modelBuilder.Entity("AGRental.Models.Properties", b =>
                {
                    b.Property<int>("Property_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("property_name");

                    b.Property<string>("address");

                    b.HasKey("Property_ID");

                    b.ToTable("Properties");

                });

            modelBuilder.Entity("AGRental.Models.User_Properties", b =>
            {
                b.Property<int>("UserID");

                b.Property<int>("PropertyID");

                b.ToTable("User_Properties");

            });

#pragma warning restore 612, 618
        }
    }
}
